CREATE TABLE Managers (
	Id			UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	Surname		NVARCHAR(50) NOT NULL,
	Name		NVARCHAR(50) NOT NULL,
	Secname		NVARCHAR(50) NOT NULL,
	Id_main_dep UNIQUEIDENTIFIER NOT NULL REFERENCES Departments( Id ),
	Id_sec_dep	UNIQUEIDENTIFIER REFERENCES Departments( Id ),
	Id_chief	UNIQUEIDENTIFIER
) 
