CREATE TABLE Sales (
	Id		  UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	ProductId UNIQUEIDENTIFIER NOT NULL REFERENCES Products(Id),
	ManagerId UNIQUEIDENTIFIER NOT NULL REFERENCES Managers(Id),
	Cnt       INT              NOT NULL DEFAULT 1,
	SaleDt    DATETIME         NOT NULL DEFAULT CURRENT_TIMESTAMP,
	DeleteDt  DATETIME         NULL
)
/*
CREATE TABLE Sales (
	id          CHAR(36) NOT NULL,    
	product_id  CHAR(36) NOT NULL COMMENT 'REFERENCES Products(Id)',
	manager_id  CHAR(36) NOT NULL COMMENT 'REFERENCES Managers(Id)',    
	sale_date   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,    
	units       INT      NOT NULL DEFAULT 1,
	delete_dt   DATETIME NULL,

	PRIMARY KEY (id)
) ENGINE = INNODB DEFAULT CHARSET = UTF8; */